#!/usr/bin/env python3
"""Write docs/data-model/diary-missing-page-refs.md: register page references
(references.csv) whose vol+page has no text in diary.csv.

Usage (PowerShell on Windows):
  python scripts/normalization/report_missing_page_refs.py
"""
import collections
import csv
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
N = ROOT / "data" / "normalized"
ORDER = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI"]

diary = collections.defaultdict(str)
for r in csv.DictReader(open(N / "diary.csv", encoding="utf-8")):
    diary[(r["vol"], r["page"])] += " " + re.sub(r"\d{3}-\d\d\s+", "", r["text"]).replace("\n", " ")
last = collections.defaultdict(int)
for v, p in diary:
    last[v] = max(last[v], int(p))
ents = {r["entity_id"]: r for r in csv.DictReader(open(N / "entities.csv", encoding="utf-8"))}
refs = list(csv.DictReader(open(N / "references.csv", encoding="utf-8")))

miss = collections.defaultdict(list)
for r in refs:
    if (r["vol"], r["page"]) not in diary:
        miss[(r["vol"], r["page"])].append(r)


def lab(r):
    return re.sub(r"\s+", " ", r["entity_label"]).strip().replace("|", "\\|")


def typ(r):
    return ents.get(r["entity_id"], {}).get("entity_type", "?")


def key_name(label):
    s = re.sub(r"\s*\(.*", "", label.split("\n")[0]).strip().rstrip(",.")
    return s.split(",")[0].strip()


def one_digit_edits(p):
    s, c = str(p), set()
    for i in range(len(s)):
        c.add(s[:i] + s[i + 1:])
        for d in "0123456789":
            c.add(s[:i] + d + s[i + 1:])
    for i in range(len(s) - 1):
        c.add(s[:i] + s[i + 1] + s[i] + s[i + 2:])
    return sorted({int(x) for x in c if x and x[0] != "0"})


def candidates(r):
    k = key_name(r["entity_label"])
    if len(k) < 3 or not r["page"].isdigit():
        return []
    pat = re.compile(r"(?<!\w)" + re.escape(k), re.I)
    return [p for p in one_digit_edits(int(r["page"]))
            if 1 <= p <= last[r["vol"]] and pat.search(diary[(r["vol"], str(p))])]


def vkey(k):
    v, p = k
    return (ORDER.index(v) if v in ORDER else 99, int(p) if p.isdigit() else 0)


xi = sorted((k for k in miss if k[0] == "XI"), key=vkey)
blank = sorted((k for k in miss if not k[0] or not k[1]), key=lambda k: -len(miss[k]))
over = sorted((k for k in miss if k[0] not in ("", "XI") and k[1]), key=vkey)
rows = lambda ks: sum(len(miss[k]) for k in ks)

o = []
w = o.append
w("# Page references without a diary page")
w("")
w("Register page references in `data/normalized/references.csv` (source: the V0.82 workbook's "
  "`RefInDiaryPage` sheet) whose (vol, page) has no text in `data/normalized/diary.csv`, which is "
  "built from the EPUB edition (vols I–X, 4,413 pages) by "
  "[`epub_diary_to_csv.py`](../../scripts/normalization/epub_diary_to_csv.py).")
w("")
w("Generated by [`report_missing_page_refs.py`](../../scripts/normalization/report_missing_page_refs.py) "
  f"on {date.today().isoformat()}.")
w("")
w(f"**{len(miss)} page keys · {rows(miss)} reference rows** "
  f"(of {len(refs):,}), in two blocks:")
w("")
w("| Block | Page keys | Reference rows | Cause | Action |")
w("|---|---:|---:|---|---|")
w(f"| [A. Vol XI](#a-vol-xi--not-in-the-epub) | {len(xi)} | {rows(xi)} | the EPUB holds vols I–X only | none needed for the EPUB — but see below: every one is Emil Hornemann and matches vol X |")
w(f"| [B. Erroneous references](#b-erroneous-page-references) | {len(over) + len(blank)} | {rows(over) + rows(blank)} | "
  f"page beyond the volume's last page ({len(over)}), or vol/page missing ({len(blank)}) | correct in the register source — "
  "see the task in [`source-field-audit.md`](source-field-audit.md#page-references-without-a-diary-page-outstanding) |")
w("")
w("Last printed page per volume in the EPUB: " +
  " · ".join(f"{v} {last[v]}" for v in ORDER if v in last) + ".")
w("")

w("## A. Vol XI — not in the EPUB")
w("")
w(f"{len(xi)} pages, {rows(xi)} references. The EPUB holds vols I–X, so these pages have no "
  "text and their diary pages say “ikke transskriberet”.")
w("")
ids = collections.Counter(r["entity_id"] for k in xi for r in miss[k])
hx = [k for k in xi if re.search(r"Hornemann", diary[("X", k[1])])]
w(f"**Finding:** all {rows(xi)} references are to one entity — "
  + ", ".join(f"`{e}` {lab(miss[xi[0]][0])}" for e in ids) +
  f" — and that entity has no vol X references at all. On {len(hx)} of the {len(xi)} pages, "
  "the same page number in **vol X** contains the name *Hornemann*. So “XI” is almost certainly a "
  "mis-keyed “X” in the register's page list for this one entry; the fix is to change the volume "
  "to X for these rows. Because the fix is certain and mechanical, it is included in the task "
  "together with block B.")
w("")
w("| Page | Refs | Entity | “Hornemann” on vol X, same page |")
w("|---:|---:|---|---|")
for k in xi:
    rs = miss[k]
    w(f"| {k[1]} | {len(rs)} | " + "; ".join(f"`{r['entity_id']}` {lab(r)}" for r in rs)
      + " | " + ("yes" if k in hx else "**no**") + " |")
w("")

w("## B. Erroneous page references")
w("")
w(f"### B1. Page number beyond the volume's last page — {len(over)} keys, {rows(over)} references")
w("")
w("The **Suggestion** column lists pages in the same volume that are one keystroke away from the "
  "recorded number (one digit dropped, changed or two digits swapped) **and** whose text contains "
  "the entity's name (surname / first word of the title). It is a lead for manual checking, "
  "not a verified correction.")
w("")
w("| Vol | Page | Last page | Entity | Type | Suggestion |")
w("|---|---:|---:|---|---|---|")
sug_n = 0
for k in over:
    for r in miss[k]:
        c = candidates(r)
        sug_n += bool(c)
        w(f"| {k[0]} | {k[1]} | {last[k[0]]} | `{r['entity_id']}` {lab(r)} | {typ(r)} | "
          + (", ".join(f"s. {p}" for p in c) if c else "—") + " |")
w("")
w(f"{sug_n} of {rows(over)} references have at least one suggestion.")
w("")
w(f"### B2. Volume or page missing — {len(blank)} keys, {rows(blank)} references")
w("")
w("| Vol | Page | Refs | What it is |")
w("|---|---|---:|---|")
notes = {
    ("", ""): "All `se:` redirect stubs (label “X, se: Y”) that were exported as page references. "
              "Not mentions at all — they belong to the alias work in "
              "[`source-field-audit.md`](source-field-audit.md#inline-se-cross-references).",
    ("IV", ""): "72 references to the same work, all without a page number.",
}
for k in blank:
    rs = miss[k]
    ids = collections.Counter(f"`{r['entity_id']}` {lab(r)}" for r in rs)
    shown = "; ".join(f"{e}" + (f" ×{n}" if n > 1 else "") for e, n in ids.most_common(4))
    more = f" … (+{len(ids) - 4} more)" if len(ids) > 4 else ""
    w(f"| {k[0] or '—'} | {k[1] or '—'} | {len(rs)} | {notes.get(k, '')} {shown}{more} |")
w("")
w("The full list of the (—, —) rows can be pulled with:")
w("")
w("```powershell")
w("python -c \"import csv; [print(r['page_id'], r['entity_id'], r['entity_label'].split(chr(10))[0]) "
  "for r in csv.DictReader(open('data/normalized/references.csv', encoding='utf-8')) if not r['vol'] and not r['page']]\"")
w("```")
w("")

out = ROOT / "docs" / "data-model" / "diary-missing-page-refs.md"
out.write_text("\n".join(o), encoding="utf-8", newline="\n")
print(len(xi), rows(xi), len(over), rows(over), len(blank), rows(blank), sug_n)
