/* nation-link.js — cross-links into nation.html (the per-nation mashup of
 * persons + places) from anywhere the reader is already looking at exactly
 * one nation.
 *
 * Three entry points into the same banner:
 *   place.html   — the place has a country ("Tyskland")        → byCountry()
 *   persons.html — the person carries a nationality ("tysk")   → byKey()
 *   places.html / persons.html list views — the reader ticked a single
 *                  Land / Nationalitet facet value             → byCountry() / byKey()
 *
 * Reads window.NATION_INDEX (data/nation-index.js, generated by
 * scripts/build_mockup/build_nation_index.py, gitignored). When that global
 * is absent — fresh clone, no build — every lookup returns null and callers
 * render nothing, so the link can never point at a nation.html that would
 * greet the reader with "data not built yet".
 *
 * Public API (window.NationLink):
 *   byKey(nationalityKey)   → info | null      ('tysk')
 *   byCountry(countryLabel) → info | null      ('Tyskland')
 *   href(info)              → 'nation.html?nat=…'
 *   html(info, context)     → banner markup string (for string-built pages)
 *   mount(el, info, context)→ fills an element, or empties it when info is null
 *
 * `info` = { key, label, category, countryLabel, persons, places }
 */
window.NationLink = (function () {
  'use strict';

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c];
    });
  }

  function available() {
    return typeof NATION_INDEX !== 'undefined' && NATION_INDEX;
  }

  function infoFor(key) {
    if (!available()) return null;
    var n = NATION_INDEX[key];
    if (!n) return null;
    var persons = (n.persons_certain || []).length;
    var places = (n.places_in_country || []).length + (n.country_entity_id ? 1 : 0);
    // A nation with nothing behind it would be a link to an empty page.
    if (!persons && !places) return null;
    return {
      key: key,
      label: n.label_da || key,
      category: n.category || '',
      countryLabel: n.country_label || null,
      persons: persons,
      places: places
    };
  }

  function byKey(key) {
    return key ? infoFor(key) : null;
  }

  /* Several nationality keys can share one country entry — hollandsk and
     nederlandsk both point at Holland, finsk and finlandssvensk both at
     Finland, and the Danish regional keys (jysk, fynsk …) sit inside
     Danmark. The Land facet only knows the country label, so pick the key a
     reader would expect: a plain national demonym before a regional or
     minority one, and among equals the one carrying the most persons. */
  var _byCountry = null;
  function buildCountryMap() {
    _byCountry = {};
    if (!available()) return;
    var best = {};
    for (var key in NATION_INDEX) {
      var n = NATION_INDEX[key];
      var label = n.country_label;
      if (!label) continue;
      var rank = (n.category === 'national') ? 0 : 1;
      var count = (n.persons_certain || []).length;
      var cur = best[label];
      if (!cur || rank < cur.rank || (rank === cur.rank && count > cur.count)) {
        best[label] = { key: key, rank: rank, count: count };
      }
    }
    for (var lab in best) _byCountry[lab] = best[lab].key;
  }

  function byCountry(countryLabel) {
    if (!countryLabel || !available()) return null;
    if (!_byCountry) buildCountryMap();
    return infoFor(_byCountry[countryLabel]);
  }

  function href(info) {
    return info ? 'nation.html?nat=' + encodeURIComponent(info.key) : 'nation.html';
  }

  function html(info, context) {
    if (!info) return '';
    var counts = [];
    if (info.persons) counts.push(info.persons.toLocaleString('da-DK') + ' personer');
    if (info.places) counts.push(info.places.toLocaleString('da-DK') + ' steder');
    return '<a class="nation-link" href="' + esc(href(info)) + '">' +
      '<div class="nation-link__body">' +
      '<div class="nation-link__title">Se alt under ' + esc(info.label) + '</div>' +
      '<div class="nation-link__meta">' +
      (context ? esc(context) + ' &nbsp;·&nbsp; ' : '') +
      esc(counts.join(' · ')) + ' samlet på én side</div>' +
      '</div><span class="nation-link__arrow">→</span></a>';
  }

  function mount(el, info, context) {
    if (!el) return;
    el.innerHTML = html(info, context);
  }

  return {
    byKey: byKey,
    byCountry: byCountry,
    href: href,
    html: html,
    mount: mount
  };
})();
