#!/usr/bin/env python3
"""
build_search_index.py
---------------------
Generates mockup/data/search-index.js — a compact `SEARCH_INDEX` array
covering every entity (persons, places, works) in
data/normalized/entities.csv plus a reference count from
references.csv. Powers the landing-page typeahead.

Each entry is a 5-tuple stored as an object for clarity:
  {l: label, t: 'p'|'s'|'w', r: reg_id, c: refs_count, w: wing}

`t` is 1-char (p=person, s=place=Sted, w=work) and `w` is the section
slug for works (bibliotek / billedkunst / teater-musik). Persons and
places don't need a wing.

Stdlib only. Reads the prepared entities.csv / references.csv published
by HCA-Diary-data-cleaning (see docs/pipeline/README.md).
"""

import csv
import json
import os
import sys
from collections import Counter

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# Shown when a prepared input is absent: this repo does not produce them.
HINT = ("the cleaning repo publishes it — run scripts/publish.py in a "
        "HCA-Diary-data-cleaning checkout (see docs/pipeline/README.md)")
ENTITIES = os.path.join(ROOT, "data", "normalized", "entities.csv")
REFS = os.path.join(ROOT, "data", "normalized", "references.csv")
OUT = os.path.join(ROOT, "mockup", "data", "search-index.js")

TYPE_CODE = {"person": "p", "place": "s", "work": "w"}


def wing_for(h2: str, h3: str) -> str:
    h2u = (h2 or "").upper()
    h3l = (h3 or "").lower()
    if "BILLEDKUNST" in h2u or "malerier" in h3l or "skulptur" in h3l or "museer" in h3l:
        return "billedkunst"
    if ("MUSIK" in h2u or "opera" in h3l or "ballet" in h3l
            or "vokal" in h3l or "skuespil" in h3l):
        return "teater-musik"
    return "bibliotek"


def main() -> None:
    if not os.path.exists(ENTITIES):
        sys.exit(f"Missing {ENTITIES} — {HINT}")

    ref_count: Counter[str] = Counter()
    if os.path.exists(REFS):
        with open(REFS, encoding="utf-8") as f:
            for r in csv.DictReader(f):
                ref_count[r["entity_id"]] += 1

    entries: list[dict] = []
    counts: Counter[str] = Counter()
    with open(ENTITIES, encoding="utf-8") as f:
        for r in csv.DictReader(f):
            etype = r.get("entity_type", "").strip()
            tcode = TYPE_CODE.get(etype)
            if not tcode:
                continue
            label = (r.get("label") or "").strip()
            if not label:
                continue
            rid = r["entity_id"]
            entry = {
                "l": label,
                "t": tcode,
                "r": rid,
                "c": ref_count.get(rid, 0),
            }
            if tcode == "w":
                entry["w"] = wing_for(r.get("genre_h2", ""), r.get("form_h3", ""))
            entries.append(entry)
            counts[etype] += 1

    # Sort by ref count descending — typeahead can then take the first N
    # rows as "popular" suggestions on focus without further sorting.
    entries.sort(key=lambda e: (-e["c"], e["l"].lower()))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/build_mockup/build_search_index.py — do not hand-edit.\n")
        f.write("// Compact search index over every entity in entities.csv. Each\n")
        f.write("// row: {l:label, t:'p'|'s'|'w', r:reg_id, c:refs, w?:wing}.\n")
        f.write("// Sorted by refs desc so SEARCH_INDEX.slice(0,N) = top-N popular.\n")
        f.write("const SEARCH_INDEX = ")
        f.write(json.dumps(entries, ensure_ascii=False, separators=(",", ":")))
        f.write(";\n")

    size_kb = os.path.getsize(OUT) / 1024
    print(f"  wrote {os.path.relpath(OUT, ROOT)}  ({size_kb:.0f} KB, {len(entries):,} entries: {dict(counts)})")


if __name__ == "__main__":
    main()
