#!/usr/bin/env python3
"""
Build per-volume print data for the cart's PDF export (mockup/cart.html).

The cart PDF reproduces each selected diary page -- text, footnotes, the full
name lists and the Det Kgl. Bibliotek link -- on its own A4 sheet. None of that
is available to cart.html (the text lives only in the generated
mockup/diary-pages/*.html, and DIARY_INDEX keeps just 3 chips per page), and
fetch() is blocked under file://, so this emits plain <script>-loadable JS,
one file per volume, loaded on demand by js/cart-pdf.js.

Reads (same sources as build_diary_pages.py, whose loaders it reuses):
  data/normalized/diary_html.csv      page markup from the EPUB edition
  data/normalized/diary.csv           text fallback + dates
  data/normalized/references.csv      entities per page
  data/normalized/entities.csv        entity label / register
  data/normalized/kb_diary_links.csv  Det Kgl. Bibliotek URL per page

Writes (gitignored -- generated, like mockup/diary-pages/):
  mockup/data/diary-print/vol-I.js … vol-X.js
    (window.DIARY_PRINT = window.DIARY_PRINT || {}).Pag040194 = {
        d: "1855-09-26",                       date / month / year heading
        k: "https://epub3.kb.dk/…",            KB URL ("" when none)
        h: "<div class=...>",                      edition markup (or <p> fallback)
        e: [["person","Reg0039110","Black, …"], …]   every register entry
    }

Scope is the same as the diary pages: only pages with transcribed text
(vols I-X) -- see _diary_scope.py.

Run from the repo root:
  python scripts/build_mockup/build_diary_print.py
"""

import json
from collections import defaultdict
from pathlib import Path

import build_diary_pages as bdp  # sibling module; scripts run from repo root

REPO_ROOT = bdp.REPO_ROOT
OUT_DIR = REPO_ROOT / "mockup" / "data" / "diary-print"

H1_TYPE = {"PERSON-REGISTER": "person", "STED-REGISTER": "place", "VÆRK-REGISTER": "work"}
H1_ORDER = ["PERSON-REGISTER", "STED-REGISTER", "VÆRK-REGISTER"]


def page_record(vol, page, ents, diary, refs, kb, markup):
    vp = (vol, page)
    rows = diary.get(vp, [])
    has_text = any(r.get("text", "").strip() for r in rows)
    body = markup.get(vp) or (bdp.diary_text_html(rows) if has_text else "")

    seen, by_h1 = set(), defaultdict(list)
    for eid in refs.get(vp, []):
        if eid in seen:
            continue
        seen.add(eid)
        e = ents.get(eid)
        if e and e["h1"] in H1_TYPE:
            by_h1[e["h1"]].append([H1_TYPE[e["h1"]], eid, e["label"]])
    entities = []
    for h1 in H1_ORDER:
        entities += sorted(by_h1.get(h1, []), key=lambda t: t[2].casefold())

    return {"d": bdp.date_range(rows), "k": kb.get(bdp.page_id(vol, page), ""),
            "h": body, "e": entities}


def main():
    print("Loading data…")
    ents = bdp.load_entities()
    diary = bdp.load_diary()
    refs = bdp.load_references()
    kb = bdp.load_kb_links()
    markup = bdp.load_page_markup()

    pages = bdp.sorted_pages(refs, diary)
    by_vol = defaultdict(dict)
    for vol, page in pages:
        if not vol or not page:
            continue
        by_vol[vol][bdp.page_id(vol, page)] = page_record(vol, page, ents, diary, refs, kb, markup)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    header = ("// Auto-generated by scripts/build_mockup/build_diary_print.py — do not hand-edit.\n"
              "// Loaded on demand by js/cart-pdf.js (file://-safe <script>, no fetch).\n")
    total = 0
    for vol, recs in by_vol.items():
        out = OUT_DIR / f"vol-{vol}.js"
        out.write_text(
            header + "window.DIARY_PRINT = window.DIARY_PRINT || {};\n"
            + "Object.assign(window.DIARY_PRINT, "
            + json.dumps(recs, ensure_ascii=False, separators=(",", ":"))
            + ");\n",
            encoding="utf-8")
        total += len(recs)
        print(f"  wrote {out.relative_to(REPO_ROOT)}  ({out.stat().st_size/1024:.0f} KB, {len(recs)} pages)")
    print(f"Done. {total} pages in {len(by_vol)} volumes.")


if __name__ == "__main__":
    main()
