"""build_timeline_index.py — Generate mockup/data/timeline-index.js from
data/normalized_v092/timeline.csv for the Tidslinje view in diaries.html.

The output is a plain <script>-loadable JS file (file://-safe, like the
diary-index pattern) defining a single global constant:

  const TIMELINE_INDEX = [
    {id, y, q, d, hda, hen, tda, ten, xda, xen},
    ...
  ]

Fields:
  id  — event_id  (T0001…)
  y   — year      (four-digit string)
  q   — quarter   ('1'–'4' or '')
  d   — date_iso  (YYYY-MM-DD or '')
  hda — year_heading_da
  hen — year_heading_en
  tda — title_da  (section heading within year, often empty)
  ten — title_en
  xda — text_da
  xen — text_en

Usage:
  python scripts/build_mockup/build_timeline_index.py
"""

import csv
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC       = REPO_ROOT / "data" / "normalized_v092" / "timeline.csv"
OUT_DIR   = REPO_ROOT / "mockup" / "data"
OUT_FILE  = OUT_DIR / "timeline-index.js"


def main() -> None:
    if not SRC.exists():
        print(f"Source not found: {SRC}")
        print("Run scripts/migration/migrate_tidstavle_sql.py first.")
        return

    rows = []
    with SRC.open(newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            rows.append({
                "id":  r["event_id"],
                "y":   r["year"],
                "q":   r["quarter"],
                "d":   r["date_iso"],
                "hda": r["year_heading_da"],
                "hen": r["year_heading_en"],
                "tda": r["title_da"],
                "ten": r["title_en"],
                "xda": r["text_da"],
                "xen": r["text_en"],
            })

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    header = (
        "// Auto-generated by scripts/build_mockup/build_timeline_index.py"
        " — do not hand-edit.\n"
        "// Loaded via <script> tag (file://-safe).\n"
    )
    OUT_FILE.write_text(
        header
        + "const TIMELINE_INDEX = "
        + json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
        + ";\n",
        encoding="utf-8",
    )
    size_kb = OUT_FILE.stat().st_size / 1024
    print(f"Wrote {OUT_FILE.relative_to(REPO_ROOT)}  ({size_kb:.0f} KB, {len(rows)} events)")


if __name__ == "__main__":
    main()
