#!/usr/bin/env python3
"""
build_persons_extra.py
----------------------
Generates mockup/data/persons-extra.js — a `PERSONS_EXTRA` JS object
with one entry per row in data/normalized/entities.csv where
entity_type == 'person'. The hand-curated `PERSONS` object inside
mockup/person.html (if any) keeps precedence; PERSONS_EXTRA fills every
other gap so any ?reg=… link to person.html resolves to real metadata
instead of a blank page.

Stdlib only. Run after scripts/normalization/hca_xlsx_to_csv.py.
"""

import csv
import json
import os
import re
import sys
from collections import Counter

ROOT     = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ENTITIES = os.path.join(ROOT, "data", "normalized", "entities.csv")
REFS     = os.path.join(ROOT, "data", "normalized", "references.csv")
OUT      = os.path.join(ROOT, "mockup", "data", "persons-extra.js")

# Life-dates parsed from labels like
#   "Aabye, Johan Peter (1818–1880)"
#   "Lyell, Mary, Lady, f. Horner (død 1873)"
#   "Aagaard, Peder (1761–1834)"
# Tolerate both en-dash and hyphen, and a "ca." prefix.
LIFE_RE   = re.compile(r"\((?:ca\.?\s*)?(\d{4})\s*[–\-]\s*(\d{4})\)")
DIED_RE   = re.compile(r"\(død\s+(\d{4})\)")


def parse_life(label: str):
    m = LIFE_RE.search(label)
    if m:
        return m.group(1), m.group(2)
    m = DIED_RE.search(label)
    if m:
        return None, m.group(1)
    return None, None


def era_for(born: str | None, died: str | None) -> str | None:
    y = born or died
    if not y:
        return None
    try:
        n = int(y)
    except ValueError:
        return None
    if n < 1700:    return "Før 1700"
    if n < 1800:    return "1700-tallet"
    if n < 1900:    return "1800-tallet"
    return "Efter 1900"


def main() -> None:
    if not os.path.exists(ENTITIES):
        sys.exit(f"Missing {ENTITIES} — run scripts/normalization/hca_xlsx_to_csv.py first.")

    print(f"Loading {os.path.relpath(ENTITIES, ROOT)}…")
    persons = []
    with open(ENTITIES, encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if r["entity_type"] == "person":
                persons.append(r)
    print(f"  {len(persons):,} persons")

    ref_count: Counter[str] = Counter()
    if os.path.exists(REFS):
        with open(REFS, encoding="utf-8") as f:
            for r in csv.DictReader(f):
                ref_count[r["entity_id"]] += 1
        print(f"  reference counts loaded for {len(ref_count):,} entities")

    # Emit one entry per person, INCLUDING IDs that mockup/person.html
    # also curates. person.html's `ALL_PERSONS = Object.assign({},
    # PERSONS_EXTRA, PERSONS)` still gives the hand-curated entries
    # precedence; emitting the extras for them too lets EntityRefs
    # (mockup/js/entity-refs.js) see the full register from any page.
    generated: dict[str, dict] = {}
    for r in persons:
        rid = r["entity_id"]
        label = (r.get("label") or "").strip()
        born, died = parse_life(label)
        generated[rid] = {
            "label":       label,
            "description": (r.get("description") or "").strip() or None,
            "born":        born,
            "died":        died,
            "era":         era_for(born, died),
            "refs":        ref_count.get(rid, 0),
        }

    print(f"  generated {len(generated):,} entries")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/build_mockup/build_persons_extra.py — do not hand-edit.\n")
        f.write("// One entry per person in PERSON-REGISTER. The hand-curated\n")
        f.write("// PERSONS object in person.html takes precedence (see ALL_PERSONS merge).\n")
        f.write("const PERSONS_EXTRA = ")
        f.write(json.dumps(generated, ensure_ascii=False, separators=(",", ":")))
        f.write(";\n")
    print(f"  wrote {os.path.relpath(OUT, ROOT)}  "
          f"({os.path.getsize(OUT)/1024:.0f} KB)")


if __name__ == "__main__":
    main()
