"""build_basemap.py — vendor an offline vector basemap for the Leaflet maps.

Replaces remote raster tiles (CARTO started returning "API KEY REQUIRED"
tiles in 2026-10) with Natural Earth vector data (public domain) committed
to the repo, so the maps work under file:// and on GitHub Pages without
any third-party tile server, key or Referer policy.

Two layers of detail, both emitted as plain <script> files (not .json, so
they load under file:// where fetch() is blocked):

  mockup/vendor/basemap/basemap-world.js   1:50m, whole world (zoom < 5)
  mockup/vendor/basemap/basemap-europe.js  1:10m, clipped to Europe and
                                           the Mediterranean (zoom >= 5)

Each defines window.HCA_BASEMAP_<WORLD|EUROPE> = {land, borders, lakes,
rivers} as GeoJSON FeatureCollections. mockup/js/basemap.js draws them.

This is a one-off vendoring step, not part of CI: the output is committed.
Re-run only to change extent or detail. Needs shapely (pip install shapely).

Usage (PowerShell on Windows):
  python scripts/build_mockup/build_basemap.py
"""

import json
import sys
import urllib.request
from pathlib import Path

try:
    from shapely.geometry import box, mapping, shape
except ImportError:
    sys.exit("shapely is required:  pip install shapely")

ROOT = Path(__file__).resolve().parents[2]
CACHE = ROOT / ".cache" / "naturalearth"
OUT = ROOT / "mockup" / "vendor" / "basemap"
NE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/"

# Europe + Mediterranean + Near East — covers ~94 % of the geocoded places
# (the rest fall back on the 1:50m world layer, which is fine for them).
EUROPE_BBOX = (-26.0, 26.0, 52.0, 72.5)

LAYERS = {
    # key: (world source, europe source, simplify tolerance world/europe in °)
    "land":    ("ne_50m_land",                         "ne_10m_land"),
    "borders": ("ne_50m_admin_0_boundary_lines_land",  "ne_10m_admin_0_boundary_lines_land"),
    "lakes":   ("ne_50m_lakes",                        "ne_10m_lakes"),
    "rivers":  ("ne_50m_rivers_lake_centerlines",      "ne_10m_rivers_lake_centerlines"),
}
TOLERANCE = {"world": 0.05, "europe": 0.005}
# Drop islets / ponds below this area (square degrees) — invisible at the
# zooms each layer is shown at, and they dominate the file size.
MIN_AREA = {"world": 0.05, "europe": 0.0005}
DECIMALS = {"world": 2, "europe": 3}


def fetch(name: str) -> dict:
    CACHE.mkdir(parents=True, exist_ok=True)
    path = CACHE / f"{name}.geojson"
    if not path.exists():
        print(f"  downloading {name} …")
        urllib.request.urlretrieve(NE + name + ".geojson", path)
    return json.loads(path.read_text(encoding="utf-8"))


def round_coords(obj, nd):
    if isinstance(obj, (list, tuple)):
        if obj and isinstance(obj[0], (int, float)):
            return [round(obj[0], nd), round(obj[1], nd)]
        out = [round_coords(o, nd) for o in obj]
        # Drop consecutive duplicate points created by rounding.
        if out and isinstance(out[0], list) and out[0] and isinstance(out[0][0], float):
            out = [p for i, p in enumerate(out) if i == 0 or p != out[i - 1]]
        return out
    return obj


def build(level: str) -> dict:
    clip = box(*EUROPE_BBOX) if level == "europe" else None
    result = {}
    for key, sources in LAYERS.items():
        src = sources[0] if level == "world" else sources[1]
        feats = []
        for f in fetch(src)["features"]:
            if not f.get("geometry"):
                continue
            g = shape(f["geometry"])
            if clip is not None:
                if not g.intersects(clip):
                    continue
                g = g.intersection(clip)
            if g.geom_type in ("Polygon", "MultiPolygon"):
                parts = [p for p in getattr(g, "geoms", [g]) if p.area >= MIN_AREA[level]]
                if not parts:
                    continue
                g = parts[0] if len(parts) == 1 else type(g)(parts) if g.geom_type == "MultiPolygon" else parts[0]
            g = g.simplify(TOLERANCE[level], preserve_topology=True)
            if g.is_empty:
                continue
            gj = mapping(g)
            feats.append({"type": "Feature", "properties": {},
                          "geometry": {"type": gj["type"],
                                       "coordinates": round_coords(gj["coordinates"], DECIMALS[level])}})
        result[key] = {"type": "FeatureCollection", "features": feats}
        print(f"  {level:6} {key:8} {len(feats):5} features")
    return result


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for level in ("world", "europe"):
        data = build(level)
        js = (f"/* Generated by scripts/build_mockup/build_basemap.py from Natural Earth "
              f"(public domain, naturalearthdata.com). Do not edit by hand. */\n"
              f"window.HCA_BASEMAP_{level.upper()} = "
              + json.dumps(data, separators=(",", ":")) + ";\n")
        path = OUT / f"basemap-{level}.js"
        path.write_text(js, encoding="utf-8")
        print(f"  -> {path.relative_to(ROOT)}  ({len(js) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
