"""build_pdf_assets.py — vendor the PDF library and fonts for the cart's PDF export.

mockup/js/cart-pdf.js writes the cart PDF directly in the browser with
pdfmake, in a Web Worker. The site also opens from file://, where a page
cannot start a worker from a script file or importScripts() another file --
so the worker is a Blob built from text, and the text has to reach the page
through an ordinary <script> tag. This packs the two things the worker needs
into one such file:

  mockup/vendor/pdfmake/pdf-assets.js
    window.HCA_PDFMAKE_SRC = "<source of pdfmake.min.js>"
    window.HCA_PDF_FONTS   = { "LiberationSerif-Regular.ttf": "<base64>", ... }

  * pdfmake -- the unmodified build is kept at
    scripts/build_mockup/vendor/pdfmake.min.js (MIT; outside mockup/ so the
    deployed site carries it only once, inside pdf-assets.js). Bump it with
    `npm pack pdfmake@<version>`, copy package/build/pdfmake.min.js over it
    and re-run this script. Licence: mockup/vendor/pdfmake/LICENSE-*.txt.
  * Liberation Serif (text) and Liberation Sans (headings) -- SIL Open Font
    License 1.1 (metric-compatible with Times New Roman / Arial), embedded in
    the PDF, which the OFL permits. Each face is subset to what the corpus
    needs: Latin (incl. Extended-A/B), IPA, combining diacritics, Greek and
    polytonic Greek, general punctuation and number forms (the diaries use
    æ ø å ½ » « – — … and, here and there, Greek and phonetic notation). That
    keeps the fonts at a few hundred KB instead of ~2 MB. The one corpus
    character Liberation lacks, ℔ (U+2114), is substituted in cart-pdf.js;
    tests/test_cart_pdf_assets.py fails if the data ever needs another.

One-off vendoring step, not part of CI: the output is committed. Re-run only
to change the pdfmake version, the font set or the character range. Needs
fontTools (pip install fonttools) and the Liberation fonts installed
(Debian/Ubuntu: fonts-liberation; Windows: download "Liberation Fonts" 2.x
and pass --fonts <folder>).

Usage (PowerShell on Windows):
  python scripts/build_mockup/build_pdf_assets.py
  python scripts/build_mockup/build_pdf_assets.py --fonts C:\\path\\to\\liberation
"""

import argparse
import base64
import io
import json
import sys
from pathlib import Path

try:
    from fontTools import subset
    from fontTools.ttLib import TTFont
except ImportError:
    sys.exit("fontTools is required:  pip install fonttools")

ROOT = Path(__file__).resolve().parents[2]
VENDOR = ROOT / "mockup" / "vendor" / "pdfmake"
PDFMAKE = ROOT / "scripts" / "build_mockup" / "vendor" / "pdfmake.min.js"
OUT = VENDOR / "pdf-assets.js"
DEFAULT_DIR = Path("/usr/share/fonts/truetype/liberation")

FACES = [
    "LiberationSerif-Regular", "LiberationSerif-Italic",
    "LiberationSerif-Bold", "LiberationSerif-BoldItalic",
    "LiberationSans-Regular", "LiberationSans-Bold",
]
UNICODES = (
    list(range(0x20, 0x7F)) + list(range(0xA0, 0x250))   # Latin-1, Latin Extended-A/B
    + list(range(0x250, 0x2B0))                          # IPA (phonetic notes in the edition)
    + list(range(0x300, 0x370))                          # combining diacritics
    + list(range(0x370, 0x400)) + list(range(0x1F00, 0x2000))   # Greek + polytonic Greek
    + list(range(0x2000, 0x2070)) + list(range(0x2100, 0x2190)) # punctuation, letterlike, number forms
    + [0x20AC]
)


def subset_face(path):
    opts = subset.Options()
    opts.layout_features = ["kern", "liga"]
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    opts.glyph_names = False
    opts.hinting = False
    opts.drop_tables += ["FFTM"]
    font = TTFont(str(path))
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=UNICODES)
    sub.subset(font)
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fonts", type=Path, default=DEFAULT_DIR, help="folder with the Liberation *.ttf files")
    args = ap.parse_args()

    vfs = {}
    for face in FACES:
        src = args.fonts / (face + ".ttf")
        if not src.exists():
            sys.exit(f"missing {src} (use --fonts <folder>)")
        data = subset_face(src)
        vfs[face + ".ttf"] = base64.b64encode(data).decode("ascii")
        print(f"  {face}: {src.stat().st_size // 1024} KB -> {len(data) // 1024} KB")

    if not PDFMAKE.exists():
        sys.exit(f"missing {PDFMAKE} (see the docstring for how to vendor pdfmake)")
    lib = PDFMAKE.read_text(encoding="utf-8")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "/* pdfmake + Liberation fonts as strings for the PDF worker -- generated by "
        "scripts/build_mockup/build_pdf_assets.py; do not edit */\n"
        "window.HCA_PDFMAKE_SRC = " + json.dumps(lib, ensure_ascii=False) + ";\n"
        "window.HCA_PDF_FONTS = " + json.dumps(vfs, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
